namespace LlmPlayground.Api.Models;

/// <summary>
/// Response model for a generated Prolog-based logic game.
/// </summary>
public sealed record GameGenerationResponse
{
    /// <summary>
    /// Whether the game generation was successful.
    /// </summary>
    public bool Success { get; init; }

    /// <summary>
    /// The game concept/idea generated by the LLM.
    /// </summary>
    public string? GameIdea { get; init; }

    /// <summary>
    /// The generated Prolog code for the game.
    /// </summary>
    public string? PrologCode { get; init; }

    /// <summary>
    /// The output from executing the Prolog game (if ExecuteGame was true).
    /// </summary>
    public string? ExecutionOutput { get; init; }

    /// <summary>
    /// Whether the Prolog code executed successfully.
    /// </summary>
    public bool? ExecutionSuccess { get; init; }

    /// <summary>
    /// Any error that occurred during execution.
    /// </summary>
    public string? ExecutionError { get; init; }

    /// <summary>
    /// Path to the generated Prolog file (if KeepGeneratedFiles is true).
    /// </summary>
    public string? GeneratedFilePath { get; init; }

    /// <summary>
    /// Number of fix attempts made to correct Prolog errors.
    /// </summary>
    public int FixAttempts { get; init; }

    /// <summary>
    /// Error message if generation failed.
    /// </summary>
    public string? Error { get; init; }

    /// <summary>
    /// The LLM provider that was used.
    /// </summary>
    public string? ProviderUsed { get; init; }

    /// <summary>
    /// Time taken for the entire generation process.
    /// </summary>
    public TimeSpan Duration { get; init; }

    /// <summary>
    /// Detailed timing breakdown for each step.
    /// </summary>
    public GenerationTimings? Timings { get; init; }
}

/// <summary>
/// Timing information for each step of game generation.
/// </summary>
public sealed record GenerationTimings
{
    /// <summary>
    /// Time taken to generate the game idea.
    /// </summary>
    public TimeSpan GameIdeaGeneration { get; init; }

    /// <summary>
    /// Time taken to generate the Prolog code.
    /// </summary>
    public TimeSpan PrologCodeGeneration { get; init; }

    /// <summary>
    /// Time taken to execute the Prolog code.
    /// </summary>
    public TimeSpan? PrologExecution { get; init; }
}

